### ISSUE TITLE
Two files are not merged correctly

### ISSUE THREAD

**Issue by deniskrumko** [mb3online/atom-snippet-manager#12]
I just wanted to test how lib is working.

```
# /Users/deniskrumko/.snippets/test.snippet.cson
'.source.python':
  'FOO':
    'prefix': 'foo'
    'body': '''
    foo
    '''
```

and

```
# /Users/deniskrumko/.snippets/test2.snippet.cson
'.source.python':
  'BAR':
    'prefix': 'BAR'
    'body': '''
    bar
    '''
```

I run command to compile result file - and there is only "BAR" in result `snippets.cson`.

Shouldn't it contain both snippets?

**Comment by ericadamski** [comment]
@deniskrumko it should contain both (ie. merge the two objects)! This is totally a bug, I will take a look in the near future. Feel free to open a PR if you are up for that as well.

**Comment by ericadamski** [comment]
Realizing now that it was only doing a shallow merge of the top most key, it really needs to do a deep merge.

**Comment by ericadamski** [comment]
See PR #13

**Comment by ericadamski** [comment]
Just published a new version (https://atom.io/packages/snippet-manager) it should be good now :)
