### ISSUE TITLE
Not able to make it work

### ISSUE THREAD

**Issue by gor0n** [mb3online/atom-snippet-manager#3]
Great plugin, it could be perfect for us but I'm not able to make it work.

I've create a test folder at the root of my project, add it to the config. Then I added a snippet file `test.snippet.cson`. But none of my snippets are loaded.

I've tried to synchronize the snippets, got the message, but it doesn't seem to work.

**Comment by ericadamski** [comment]
@gor0n could you check the developer tools and see if there are any issues? I would love to get this working for you!

**Comment by gor0n** [comment]
I got `Uncaught (in promise) Error: ENOENT: no such file or directory, scandir 'test'(…)`

My test folder is at the root of my project, in the config I tried `test`, `/test` and `./test`.

**Comment by pvienneau** [comment]
Can you try setting the config value to the absolute path of your test folder?

**Comment by gor0n** [comment]
I's working with a absolute path!

But it seems to override my current snippet file. My snippets are not accessible anymore, only the one added in my project is working. I thought it was like a concatenation :(

The idea is to let people from my team have their own snippets, then have some snippets added depending of the framework used by the project.

**Comment by ericadamski** [comment]
@gor0n It should do concatenation, the algorithm is as follows:

* read in all snippets found into JSON objects
* read in `~/.atom/snippets.cson` into JSON object
* merge the snippets object with the list of all other JSON objects.

Another question, what OS are you running on? Node should sanitize file paths but it may be messing with things as well.

**Comment by ericadamski** [comment]
@gor0n [this function](https://github.com/mb3online/atom-snippet-manager/blob/develop/lib/manager.js#L52) is where the concat should be done, it is possible the logic is skewed? You could take a look.

**Comment by gor0n** [comment]
I'm on OSX.

I see an alias to test.snippet.cson from my project in the atom/snippets directory and the path to the main snippets.cson seems correct because when I do synch my snippets.cson is modified (it strips all comments).

**Comment by ericadamski** [comment]
But you said that it removed all the snippets in the main snippets.cson?

**Comment by gor0n** [comment]
Well I can't use them anymore in atom. But I still can see them in the snippets.cson file.

**Comment by gor0n** [comment]
This is my test.snippets.cson

```
'.source.css.scss':
# Components
    'mixin test':
        'prefix': 'mixin.test'
        'body': '@include test()'
```

**Comment by ericadamski** [comment]
can you send me the main snippets file as well? possibly a generation error

**Comment by gor0n** [comment]
Ok got it. The problem is when you use the same scope for extensions

I used `.css.scss` in my general `snippets.cson` but also in my `test.project.cson`. It seems I'm only able to use the snippets defined in the last object.

**Comment by ericadamski** [comment]
do you mind sending me that file so that I can do some testing?

**Comment by ericadamski** [comment]
@gor0n, PR #4 should fix your issue, if it doesn't please reopen this issue 😄
